### ISSUE TITLE
App de tracking - Mobile

### ISSUE THREAD

**Issue by vaniaon** [sosbrumadinho/ideas_and_requests#11]
Prezados,

Precisamos de desenvolvedor mobile para um app de tracking. Quem puder ajudar, por favor, coloquem sua experiência e conhecimento nessa issue aqui!!!

Obs: demanda da Vale. Terá que dar continuidade a um app que eles já iniciaram com  Ionic e  usando firebase como backend. O app precisa ser para Android e IOS

**Comment by RodriguesCSI** [comment]
Olá @vaniaon, o app precisa ser para IOS também?

**Comment by vaniaon** [comment]
@RodriguesCSI vou procurar saber

**Comment by luizblanes** [comment]
Fiz um app tipo uber usando ionic3 e firebase.

**Comment by vaniaon** [comment]
@RodriguesCSI  Precisa ser Android e IOS. Atualizando a descrição

**Comment by RodriguesCSI** [comment]
Não tenho experiência em desenvolvimento hibrido ou IOS, somente Android

**Comment by pictos** [comment]
@vaniaon não tenho conhecimento em Ionic. Se permitirem eu posso iniciar o app do zero, não posso falar quanto tempo levarei para chegar até o ponto atual sem antes ver como o projeto está.

Tenho conhecimento em Xamarin, ferramenta que permite desenvolver aplicativos para diversas plataformas, compartilhando código e entregando uma aplicação nativa. Trabalho com a ferramenta há +- 4 anos e atualmente contribuo com o projeto dela (que é open source).

**Comment by mpinheir** [comment]
@vaniaon Onde está o repositório da App?

**Comment by cfguimaraes** [comment]
Todo o meu conhecimento a disposição, completamente apto para as tecnologias citadas, só não tenho um device com Ios para testes.
Consigo fazer todo o desenvolvimento com o que tenho de recursos.
Liberação do app para iPhone vou precisar de um tester, só para garantir

**Comment by mpinheir** [comment]
@cfguimaraes iOS eu testo aqui se precisar.

**Comment by mpinheir** [comment]
Aparentemente o @erick220 colocou o projeto da app que ele criou em: 
@https://github.com/Erick2280/sosbrumadinholocalizador

**Comment by vaniaon** [comment]
@mpinheir não me forneceram ainda.

**Comment by mpinheir** [comment]
@vaniaon Não seria este repo que eu postei acima?

**Comment by cfguimaraes** [comment]
Eu dei uma olhada no código desse repositório, é um bom start, precisa integrar o Firebase nele.
Para o que é realmente necessário já dá para começar.

Se o interesse de uso for ficar coletando dados periodicamente do usuário em campo, a gente pode já entregar esse app com essa funcionalidade e consumir esses dados num mapa de calor usando o Google maps

**Comment by Erick2280** [comment]
> Eu dei uma olhada no código desse repositório, é um bom start, precisa integrar o Firebase nele.
> Para o que é realmente necessário já dá para começar.
> 
> Se o interesse de uso for ficar coletando dados periodicamente do usuário em campo, a gente pode já entregar esse app com essa funcionalidade e consumir esses dados num mapa de calor usando o Google maps

Posso implementar o Firebase.
Infelizmente não tenho nenhum dispositivo iOS, portanto não terei como gerar arquivos de instalação para o iPhone.

**Comment by mpinheir** [comment]
@Erick2280 eu tenho iOS e Android aqui no lab. Eu posso testar.

**Comment by mpinheir** [comment]
@Erick2280 Acredito que o Android seja muito mais comum no Brasil do que o iPhone. Vamos aguardar a orientacao da @vaniaon sobre o que 'e preciso.

**Comment by cfguimaraes** [comment]
Concordo, acredito que todas as dependências foram resolvidas, no tocante a desenvolvimento.
Faltam agora as informações da @vaniaon relacionadas a algum possível trabalho em andamento e também algum requisito que nos tenha faltado.
Obrigado @mpinheir e @erick2280

**Comment by RodriguesCSI** [comment]
Vi que o app em Ionic está escrito em Angular. Como trabalho com Angular posso ajudar tanto no desenvolvimento quanto na revisão.

**Comment by jersobh** [comment]
@vaniaon https://dataforge.com.br/brumadinho
Já está funcionando, com mapa de calor.

**Comment by jersobh** [comment]
![](https://i.imgur.com/x4avN3b.png)
![](https://i.imgur.com/nhez1wJ.png)
![](https://i.imgur.com/7grhN2u.png)
![](https://i.imgur.com/BNWMxkt.png)

**Comment by mpinheir** [comment]
@vaniaon ainda há necessidade disso ou podemos fechar o issue?

**Comment by vaniaon** [comment]
Oi, pessoal! Ainda estamos alinhando com a Vale, então deixa aberto por enquanto.
Obrigada!

**Comment by mpinheir** [comment]
@vaniaon Já faz quase 1 mês desde a Tragédia e a VALE ainda não sabe do que precisa em termos de software? A VALE não tem um kit de emergência e uma equipe de emergência?

**Comment by pictos** [comment]
@mpinheir  não posso responder diretamente pela Vânia, mas essa demanda não é apenas da Vale.

**Comment by vaniaon** [comment]
Oi, @mpinheir . A Vale contratou uma pessoa para ficar em contato direto com a gente e alinhar com o que ela já tem. Essa pessoa começou a fazer isso na semana passada e acredito que essa semana já temos uma resposta.
A demanda dessa issue, em específico, partiu da Vale. No entanto, como vc pode verificar em outras issues, a Vale não é nossa única requisitante. Estamos atendendo qualquer entidade que precise de uma solução que possa ajudar Brumadinho em curto, médio e longo prazo bem como prevenir que outras tragédias como essa aconteça.

Nesse momento estamos atendendo apenas a demandas urgentes (por ex, localização de corpos e identificação das vítimas). Essas demandas não são da Vale, mas da equipe de resgate. 

Como a comunidade cresceu muito rápido, em paralelo a isso, estamos nos organizando para evitar retrabalho. Arquitetos de software estão mapeando softwares existentes bem como o que já foi desenvolvido aqui. Esperamos voltar os desenvolvimentos essa semana com todo vapor! 

Sugiro também ir acompanhando as discussões no nosso grupo do Telegram: https://t.me/joinchat/DQBYpBdvDrhVA6EQwXZ9gg

Muito obrigada,
Vânia

**Comment by cfguimaraes** [comment]
Depois de tanto tempo, nenhuma evoluçao efetiva, sugiro fechar essa issue.
Até mesmo porquê já foram postadas soluções efetivas ao problema central pelo @jersobh.

**Comment by pictos** [comment]
@cfguimaraes essa issue já foi resolvida. Obg a todos pela participação. 

Nossa equipe está agora atendendo a outras demandas, se vocês quiserem contribuir fiquem atentos a esse repositório : https://github.com/sosbrumadinho/Collaboration_Platform . 

Maiores informações serão passadas por lá, no decorrer da semana.
